# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - '*'
    exclude:
    - l10n_master

pool:
  vmImage: 'vs2017-win2016'

name: $(Rev:r)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- powershell: |
    choco install cloc --no-progress
    cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git
  displayName: 'Cloc'

- script: |
    node --version
    call npm --version
  displayName: 'Version checks'

- script: call npm install
  displayName: 'npm install'

- script: call npm run build
  displayName: 'npm run build'
