image:
- Visual Studio 2017

init:
- ps: |
    if($isWindows -and $env:DEBUG_RDP -eq "true") {
      iex ((new-object net.webclient).DownloadString(`
        'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    }
- ps: Install-Product node 10

install:
- ps: choco install cloc --no-progress
- ps: cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git

before_build:
- cmd: node --version
- cmd: npm --version

build_script:
- cmd: npm install
- cmd: npm run build
- cmd: npm run test
- cmd: 7z a coverage-%APPVEYOR_BUILD_NUMBER%.zip coverage\*

on_finish:
  - ps: |
      if($isWindows -and $env:DEBUG_RDP -eq "true") {
        $blockRdp = $true
        iex ((new-object net.webclient).DownloadString(`
          'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }

artifacts:
- path: coverage-%APPVEYOR_BUILD_NUMBER%.zip
